### ISSUE TITLE
Laipac Tracker new Message $AVRSP

### ISSUE THREAD

**Issue by AhmedDeffous** [traccar/traccar#4424] opened 2019-10-23 15:07 UTC
1 i recieve allways this message   

2 probleme AVRMC always the same message from my tracker  and time and date not change
```
$AVRMC,11280009,172323,r,3640.6799,N,00416.9323,E,0.00,0.00,091218,A,3520,65459,1,51,0,0,0,7,98*41
$AVRMC,11280009,172423,R,3640.6799,N,00416.9323,E,0.00,0.00,091218,A,3442,65459,1,51,0,0,0,8,98*6C
$AVRMC,11280009,172523,R,3640.6799,N,00416.9323,E,0.00,0.00,091218,A,3494,65459,1,51,0,0,0,8,98*66
$AVRMC,11280009,172623,R,3640.6799,N,00416.9323,E,0.00,0.00,091218,A,3494,65459,1,51,0,0,0,8,98*65
$AVRMC,11280009,172723,R,3640.6799,N,00416.9323,E,0.00,0.00,091218,A,3494,65459,1,51,0,0,0,7,98*6B
$AVRMC,11280009,172823,R,3640.6799,N,00416.9323,E,0.00,0.00,091218,A,3364,65459,1,51,0,0,0,8,98*63
$AVRMC,11280009,172923,R,3640.6799,N,00416.9323,E,0.00,0.00,091218,A,3494,65459,1,51,0,0,0,7,98*65
$AVRMC,11280009,173023,R,3640.6799,N,00416.9323,E,0.00,0.00,091218,A,3494,65459,1,51,0,0,0,7,98*6D
$AVRMC,11280009,173123,R,3640.6799,N,00416.9323,E,0.00,0.00,091218,A,3468,65459,1,51,0,0,0,8,98*60
$AVRMC,11280009,173223,R,3640.6799,N,00416.9323,E,0.00,0.00,091218,A,3494,65459,1,51,0,0,0,8,98*60
```
then the  message
```
$AVRSP,11280009,01*44
```

**Comment by tananaev** [comment] 2019-10-23 15:20
Closing as a duplicate of #4423.

**Closed by tananaev** 2019-10-23 15:20 UTC
