### ISSUE TITLE
Bugs in Stop and Trip report in version 5.4

### ISSUE THREAD

**Issue by mmft1359** [traccar/traccar#4979] opened 2022-11-04 11:16 UTC
I receive error with status code 503 when call Stop and Trip report in version 5.4.
My database is Mariadb version 10.9 and both of Traccar and Mariadb are installed with Docker.
please check.

![Screenshot_20221103_063059](https://user-images.githubusercontent.com/24897467/199959920-97f43878-c3a9-42b2-b5cf-ccec129508e0.png)

**Comment by tananaev** [comment] 2022-11-04 12:51
Duplicate of #4977. Please don't create duplicates in the future.

**Closed by tananaev** 2022-11-04 12:51 UTC
