### ISSUE TITLE
psql: ERROR: column "geofenceids" of relation "tc_devices" does not exist

### ISSUE THREAD

**Issue by bzed** [traccar/traccar#4948] opened 2022-09-13 14:33 UTC
Running 5.3 on a fresh pgsql 13 database results in

```
error - ERROR: column "geofenceids" of relation "tc_devices" does not exist
  Position: 23 - PSQLException (... < QueryBuilder:473 < DatabaseStorage:108 < GeofenceEventHandler:82 < ...)
```
Thats the created table:
```
                                       Table "public.tc_devices"
     Column     |            Type             | Collation | Nullable |             Default              
----------------+-----------------------------+-----------+----------+----------------------------------
 id             | integer                     |           | not null | generated by default as identity
 name           | character varying(128)      |           | not null | 
 uniqueid       | character varying(128)      |           | not null | 
 lastupdate     | timestamp without time zone |           |          | 
 positionid     | integer                     |           |          | 
 groupid        | integer                     |           |          | 
 attributes     | character varying(4000)     |           |          | 
 phone          | character varying(128)      |           |          | 
 model          | character varying(128)      |           |          | 
 contact        | character varying(512)      |           |          | 
 category       | character varying(128)      |           |          | 
 disabled       | boolean                     |           |          | false
 status         | character(8)                |           |          | 
 geofenceIds    | character varying(128)      |           |          | 
 expirationtime | timestamp without time zone |           |          | 
Indexes:
    "tc_devices_pkey" PRIMARY KEY, btree (id)
    "idx_devices_uniqueid" btree (uniqueid)
    "tc_devices_uniqueid_key" UNIQUE CONSTRAINT, btree (uniqueid)
Foreign-key constraints:
 [.....]
```

Postgresql default to lowercase, if you want case sensitive names, quotes are needed:

```
traccar=# select geofenceIds from tc_devices;
ERROR:  column "geofenceids" does not exist
LINE 1: select geofenceIds from tc_devices;
               ^
HINT:  Perhaps you meant to reference the column "tc_devices.geofenceIds".
traccar=# select "geofenceIds" from tc_devices;
 geofenceIds 
-------------
 
 
 
(3 rows)

traccar=# 
```

But the generated sql query does not use quotes:
```
2022-09-13 16:18:42.415 CEST [231931] traccar@traccar ERROR:  column "geofenceids" of relation "tc_devices" does not exist at character 23
2022-09-13 16:18:42.415 CEST [231931] traccar@traccar STATEMENT:  UPDATE tc_devices SET geofenceIds = $1 WHERE id = $2
```

Renaming the column just works well:
```
alter table tc_devices rename COLUMN "geofenceIds" TO "geofenceids";
```

**Comment by tananaev** [comment] 2022-09-13 14:41
Duplicate of https://github.com/traccar/traccar/issues/4945.

**Closed by tananaev** 2022-09-13 14:41 UTC
