### ISSUE TITLE
unable to locate device

### ISSUE THREAD

**Issue by josephphale** [traccar/traccar#2157] opened 2016-07-25 14:35 UTC
I installed traccar both client and server..Registered a mobile device on the server but cant show location of the device on the map

**Comment by tananaev** [comment] 2016-07-25 22:19
Please follow instructions here:

https://www.traccar.org/troubleshooting/

**Comment by josephphale** [comment] 2016-07-26 08:02
![pic1](https://cloud.githubusercontent.com/assets/20638654/17130272/ffe8304e-5317-11e6-8cf1-81e3e29bfc86.png)

**Comment by josephphale** [comment] 2016-07-26 08:03
i think thats why i cant see my device on the map on the server

**Comment by tananaev** [comment] 2016-07-26 09:51
That's definitely a problem. Are you sure port is visible? What port are you using?

**Comment by josephphale** [comment] 2016-07-26 11:46
5055

**Comment by tananaev** [comment] 2016-07-26 11:48
What about the second question?

**Comment by josephphale** [comment] 2016-07-26 11:48
its is visible on my mobile phone on traccar mobile app thats server port....and server address is 192.168.1.149

**Comment by tananaev** [comment] 2016-07-26 11:50
OK, so it's on the same local network, right? What do you see in the logs?

**Comment by josephphale** [comment] 2016-07-26 11:51
This what i see on the tracker server.log

2016-07-26 07:18:18  INFO: Operating system name: Windows 7 version: 6.1 architecture: amd64
2016-07-26 07:18:18  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.5-b02
2016-07-26 07:18:18  INFO: Memory limit heap: 1812mb non-heap: 0mb
2016-07-26 07:18:18  INFO: Character encoding: UTF-8 charset: UTF-8
2016-07-26 07:18:18  INFO: Version: 3.5-SNAPSHOT
2016-07-26 07:19:15  INFO: Starting server...
2016-07-26 08:56:22  INFO: Shutting down server...
2016-07-26 09:03:26  INFO: Operating system name: Windows 7 version: 6.1 architecture: amd64
2016-07-26 09:03:26  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.5-b02
2016-07-26 09:03:26  INFO: Memory limit heap: 1812mb non-heap: 0mb
2016-07-26 09:03:26  INFO: Character encoding: UTF-8 charset: UTF-8
2016-07-26 09:03:26  INFO: Version: 3.5-SNAPSHOT
2016-07-26 09:03:51  INFO: Starting server...

**Comment by tananaev** [comment] 2016-07-26 11:53
Nothing from the device. It means that server doesn't receive anything.

**Comment by josephphale** [comment] 2016-07-26 11:54
So it means maybe its a problem with server address??

**Comment by tananaev** [comment] 2016-07-26 11:55
I can only guess where the problem is, but you must be missing something somewhere.

**Comment by josephphale** [comment] 2016-07-26 11:56
how should i tackle this because i tried reinstalling but still the same

**Comment by tananaev** [comment] 2016-07-26 11:58
Well, I would recommend to follow troubleshooting guide. Make sure the port is visible from your device.

**Comment by josephphale** [comment] 2016-07-26 12:00
port is visible from my device because it is stated there....but i tried this link https://www.traccar.org/port-check/ to check the port it said the port is closed

**Comment by tananaev** [comment] 2016-07-26 12:21
What do you mean by "is stated there"? Link won't work because you are using local IP address.

**Comment by josephphale** [comment] 2016-07-26 12:26
traccar client app at server port.And which IP address am I supposed to use??

**Comment by tananaev** [comment] 2016-07-26 22:53
You need to use your server IP address and port 5055.

**Comment by josephphale** [comment] 2016-07-27 06:18
How can i find the IP address i am using??

**Comment by tananaev** [comment] 2016-07-27 06:22
Do you want to use public or local address. Local you can check in network settings. For public you can ask your ISP.

**Comment by josephphale** [comment] 2016-07-27 06:51
I just tried with a local IP address,same responses

**Comment by tananaev** [comment] 2016-07-27 07:01
Try to open following URL in browser on your mobile device:

http://your.ip.address:5055

**Comment by josephphale** [comment] 2016-07-27 08:18
Its does not show..it says the webpage is not available

**Comment by tananaev** [comment] 2016-07-27 08:46
It means that port is closed.

**Comment by josephphale** [comment] 2016-07-27 09:03
So what should i do to fix these

**Comment by sunhoww** [comment] 2016-07-30 18:32
@josephphale if your are running the server behind a router, you should probably _port forward_. google or go to [http://portforward.com/](http://portforward.com/)

recommend closing this issue.

**Closed** 2022-06-22 13:15 UTC
