### ISSUE TITLE
SMS Sending error in 6.5

### ISSUE THREAD

**Issue by jinzo** [traccar/traccar#5413] opened 2024-09-19 20:18 UTC
Hi,

continuing from the forum thread: https://www.traccar.org/forums/topic/sms-notification-errorafter-upgrade-to-65-version/page/
The problem is that the constructed JSON (for some reason) inserts another newline (unescaped) at the end of "message" - and this is then invalid JSON and fails with most parsers ( `"Test message\n` ) in below example:

> '{\n'
>  '            "to": "+1234",\n'
>  '            "message": "Test message\n'
>  '"\n'
>  '        }'

(this is a line by line representation of what gets posted quoted with single quotes).

Not entirely sure why this is happening after the upgrade, it for sure did not happen before. Will continue debugging.

**Comment by jinzo** [comment] 2024-09-19 20:23
Ah, unintended side effect of https://github.com/traccar/traccar/commit/9fc42e046178bbc19e3d7ac1282636a32d565f8e
So I guess, changing this to trim just the right part of the string would 'solve' this problem (as teltonika username and password are always on the left side/start of the string). Or going back up the stack and see why the message has a newline in the first place.

**Comment by tananaev** [comment] 2024-09-19 20:56
Probably figuring out why there's a new line is what we should do first.

**Comment by tananaev** [comment] 2024-09-19 22:24
https://github.com/traccar/traccar/issues/5402#issuecomment-2362293674

**Comment by jcardus** [comment] 2024-09-19 22:56
The problem is just with the test notification?

**Comment by tananaev** [comment] 2024-09-19 22:57
I don't see any indication that it's limited to just test notifications.

**Comment by jcardus** [comment] 2024-09-19 23:04
I'll take a look

**Comment by truppelito** [comment] 2024-09-19 23:08
No, I can confirm it's not. In fact, I found the issue because I stopped receiving notifications during normal operation. I showed the test notification because that's just how I debugged it.

**Comment by jcardus** [comment] 2024-09-19 23:11
It's related with the templates, when the message comes from the template it comes with new lines, maybe we should trim in the notification part and not on the sms side.

**Comment by jcardus** [comment] 2024-09-19 23:27
https://github.com/traccar/traccar/pull/5414

this should fix it

**Comment by truppelito** [comment] 2024-09-19 23:39
Can I suggest that the json payload also be escaped after substituting the strings? It could help prevent similar issues in the future and would make the code more robust.

**Comment by jcardus** [comment] 2024-09-20 00:44
I don't think that makes sense, you have to escape the string contents in the json, not the json payload. So, maybe the correct way would be to escape the string instead of trimming it.

**Comment by tananaev** [comment] 2024-09-20 04:39
Fixed in https://github.com/traccar/traccar/commit/66b538f03690c34eae6c74086207b472e8f5c55c and https://github.com/traccar/traccar/commit/f53d4c24cd7cc4b7cbd3bd043f8d1e95c72d24e4.

**Closed by tananaev** 2024-09-20 04:39 UTC

**Comment by truppelito** [comment] 2024-09-20 08:08
> I don't think that makes sense
Yes sorry, I meant escape the json values, not the entire payload.

**Comment by tananaev** [comment] 2024-11-19 19:32
There's an easy workaround. Just update templates.
