### ISSUE TITLE
Microsoft sql database error

### ISSUE THREAD

**Issue by Esra12344** [traccar/traccar#4658] opened 2021-03-31 22:04 UTC
When I write sql information in traccar.xml and leave debug.xml the same, the tables do not come to the database. but when I write the database information in debug.xml, the tables come in microsoft sql server. But then I get 2 errors.
1.
```
Caused by: java.lang.IllegalMonitorStateException
```
2.
```
Execution failed for task ': Main.main ()'.
> Process 'command' C: / Program Files / Java / jdk-15.0.1 / bin / java.exe '' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

When I do not change the debug.xml and write the database information to traccar.xml, the tables are not created and the information in the database is not updated when the user logs in and logs in.

What kind of path should I follow? Thanks.

**Comment by tananaev** [comment] 2021-03-31 22:09
Looks like a duplicate of:

https://www.traccar.org/forums/topic/tables-appear-in-the-database-but-i-get-an-error/

**Closed by tananaev** 2021-03-31 22:09 UTC

**Comment by Esra12344** [comment] 2021-03-31 22:17
There is no result on this link. What is the solution? Please

**Comment by Esra12344** [comment] 2021-03-31 22:19
When I just write the database information to traccar.xml, the database is not created and the information is not sent to the tables.

**Comment by tananaev** [comment] 2021-03-31 22:24
If you didn't receive a response on the forum, it doesn't mean it's ok to duplicate the thread here.

**Comment by Esra12344** [comment] 2021-03-31 22:41
I'm sorry I did not understand :( Do you know the answer to my question? Please
