### ISSUE TITLE
Old interface feature not ported to new look - clicking on path replay doesnt show timestamp

### ISSUE THREAD

**Issue by interduo** [traccar/traccar#4951] opened 2022-09-23 13:39 UTC
**Describe the bug**
I updated the traccar (to 5.3) from very old interface (I think 2.x or 3.x). In old interface we could click on path in replay module and get the time in popup. I the car is going here and backwards few time but another way this is very complicated to find the right timestamp by using slider left-to-right few times. From our point of view this is UX regresion.

**Expected behavior**
Clicking on path in replay module should open the tip/overlay small border with human readable timestamp of the path object.

**Screenshots**
![image](https://user-images.githubusercontent.com/17087236/191972507-0f91b17f-e1d9-4c39-b374-c9f44978fc77.png)

**Comment by tananaev** [comment] 2022-09-23 14:28
Seems like a duplicate of https://github.com/traccar/traccar-web/issues/1010.

**Closed by tananaev** 2022-09-23 14:28 UTC
