### ISSUE TITLE
Google maps api - option to use

### ISSUE THREAD

**Issue by alijnclarke** [traccar/traccar#2991] opened 2017-03-10 17:52 UTC
So i know that currently it's possible to use google maps as a custom map layer, by entering a crafted url (their tile server). 

However that is almost certainly against their terms and conditions, so i'd ask if you'd consider adding an option to use their api (with the ability to enter creds etc), this would also allow the use of more map styles / kinds.

**Comment by tananaev** [comment] 2017-03-10 21:59
To use Google Maps in Traccar, you have to use "Premium Plan" which is very expensive. You can't use free or even a regular paid version. Also, if you are paying for premium plan, it's likely that they will allow you to use tile server directly.

**Comment by ali-raza101** [comment] 2018-07-19 10:11
Hi @tananaev, I can confirm that Google allow you to access maps only via their given APIs in cloud console. 
**All other means of accessing maps is prohibited and that application/domain will be blocked.** I have Google's Premium License but they have given 17 MAP APIs and confirmed that direct access of tile server is prohibited. 

It means now we can integrate Google Maps in TRACCAR (or any other app) only by integrating following:
**1. Google Static Maps API** (http call request by giving coordinates instead of tile number {x},{y})
**2. Google Maps JavaScript API** (need a lot of changing in traccar code)

We all know Google map are most updated, enriched and continuously growing, almost all big apps like Uber and Careem use it. Hope you will consider resolving this issue. Thanking you in anticipation.

**Comment by tananaev** [comment] 2018-07-19 10:16
There are some hacks to integrate Google Maps API with OpenLayers, but I don't like it.

**Comment by ali-raza101** [comment] 2018-07-19 10:50
Ok sir but this feature is highly demanding and needed for a better tracking expirience. OSM has wrong names of all roads and has very less places information that's why we need Google Maps. Can you please help a little bit in this regard.

From the documentation here https://www.traccar.org/map-layers/ ,this url gives us 3 values (x y=tile numbers, z=zoom) each time we interact with the map to get a new TILE image.
`https://mt0.google.com/vt/lyrs=m&hl=en&x={x}&y={y}&z={z}&s=Ga`

This URL is from Google Static Maps API documentation here https://developers.google.com/maps/documentation/maps-static/dev-guide 
`https://maps.googleapis.com/maps/api/staticmap?center=**{latitude},{longitude}**&zoom={z}&size=400x400&key=YOUR_API_KEY`

All we need is to parse latitude and longitude instead of {x},{y} tile numbers. Is this the right approach or we have to manipulate Open-layers code?

**Comment by tananaev** [comment] 2018-07-19 10:52
How much would static map API cost if we load each tile like that?

**Comment by tananaev** [comment] 2018-07-19 10:53
Also, it seems like Google attribution will be added to every tile.

**Comment by ali-raza101** [comment] 2018-07-19 14:14
After the new pricing plans of 2018 now I think any small scale business can use Google Maps. Just view their pricing which Google sent me in email here when I contact their sales department for premium License https://cloud.google.com/maps-platform/pricing/sheet/
Up to 100,000 loads totally free then you will be charged $2 for next 100,000 load and then price decreases even further, you will be charged $1.60 upto 500,000 loads. 

Another Good news is that in native mobile apps of Android and iOS there will be unlimited free map loads by integrating their Maps SDK into native apps receptively. 😃

**Comment by tananaev** [comment] 2018-07-19 17:04
There's still a problem with attribution label.

**Comment by ali-raza101** [comment] 2018-07-22 00:01
Yes that is the problem I've tried it manually and on each tile there is a name attricution on bottom left corner and date on top right corner of each tile. Which ultimatley leads to useless tiles.

**I was searching and found a better option, How about Google Maps EMBED Api?** 
https://developers.google.com/maps/documentation/embed/guide#place_mode

The calls of this Api only count 1-map-load when application launch and then if user interact for several hours with the map (like zooming, panning etc), it will not be counted as new map loads, so technically it will be billed zero on even "Unlimited loads".

**Comment by ali-raza101** [comment] 2018-07-22 00:11
And we have another option of Google Maps JavaScript APi.
https://developers.google.com/maps/documentation/javascript/tutorial?hl=en_US

But I think it is less economic in terms of pricing than Static or Embeded maps APIs. Please have a look at both Api links above. Thanks

**Comment by tananaev** [comment] 2018-07-22 00:39
I don't see how embedded map is an option here. As for Maps API, it would mean re-writing our whole web app.

**Comment by ali-raza101** [comment] 2018-07-23 06:18
So what can be the best possible option to integrate Google Maps into traccar? Or you have any other ideas (as Google has forbidden any direct or indirect access to maps except via Maps APIs mentioned above)

**Comment by tananaev** [comment] 2018-07-23 06:51
Here's one of the easy options:

https://github.com/mapgears/ol3-google-maps

**Comment by ali-raza101** [comment] 2018-07-24 13:00
And when we can hope Traccar will officially support Google Maps legally in compliance to their TOS?

**Comment by tananaev** [comment] 2018-07-24 13:03
When someone implement it.

**Comment by ali-raza101** [comment] 2018-07-24 13:07
someone from public? or someone from your team?

**Comment by tananaev** [comment] 2018-07-24 13:08
Either.

**Comment by ali-raza101** [comment] 2018-07-24 13:13
Alright, I'm not pro but let me try it on a separate server, let's see if there is a positive outcome.

**Comment by ali-raza101** [comment] 2018-07-24 13:17
In case I didn't succeed, then we will wait for you great effort and input in this regard and see this feature in Traccar Official Release.  😊

**Comment by ali-raza101** [comment] 2018-11-15 10:12
Dear @tananaev , I'm unable to understand this implementation as I said earlier I'm not a pro. So I'm creating a feature request for this. I've stoped using Google maps tile server url to avoid blocking of domain due to legal TOS. 

**Please do have a look into this. Request Link: https://github.com/traccar/traccar/issues/4143 Thanks a lot.**

**Comment by ali-raza101** [comment] 2018-11-24 14:03
@tananaev please respond.

**Comment by tananaev** [comment] 2022-07-04 13:56
Closing. This should be moved to the web app repo. I believe there's already a request for it there.

**Closed by tananaev** 2022-07-04 13:56 UTC
