### ISSUE TITLE
Web e-mail

### ISSUE THREAD

**Issue by sms1515** [traccar/traccar#3048] opened 2017-03-23 22:01 UTC
Hi, I've tried to deploy in several ways, send email notification, but it does not work
```xml
<entry key='mail.smtp.host'>smtp.mail.yahoo.com.br</entry>
<entry key='mail.smtp.port'>465</entry>
<entry key='mail.smtp.ssl.enable'>true</entry>
<entry key='mail.smtp.from'>xxxxxxxxxxx@yahoo.com.br</entry>
<entry key='mail.smtp.auth'>true</entry>
<entry key='mail.smtp.username'>xxxxxxxxxxx@yahoo.com.br</entry>
<entry key='mail.smtp.password'>xxxxxxxxxxx</entry>
```
Can you help me with this?
Another thing, the building, is not it always that shows, something that can be done?

**Comment by tananaev** [comment] 2017-03-23 22:11
What's the error message?

What bout building?

**Comment by sms1515** [comment] 2017-03-23 22:15
I tried, include this setting in traccar.xml and also default.xml

**Comment by tananaev** [comment] 2017-03-23 22:29
You haven't answered any of my questions.

**Comment by sms1515** [comment] 2017-03-23 22:44
Unconnected email.

It is not always that it shows the current address of the device

**Comment by tananaev** [comment] 2017-03-23 22:51
Please provide a screenshot of the error.

As for address, it's not related to the email protocol, so if you want to discuss it, create a separate thread. I think the problem is just that geocoder doesn't return any data.

**Comment by sms1515** [comment] 2017-03-23 22:54
I just wanted to enjoy it, right here, I'll create another

**Comment by sms1515** [comment] 2017-03-23 23:07
Do you recommend some program to back up in the database? I use the default database.

**Comment by tananaev** [comment] 2017-03-24 00:24
How is this question related to the topic? Why are you asking random questions? Is the email problem fixed? Can we close this issue?

**Closed** 2022-07-01 14:18 UTC
