### ISSUE TITLE
Enable filter Error！

### ISSUE THREAD

**Issue by gpsim** [traccar/traccar#3958] opened 2018-06-30 02:51 UTC
Hello，
Latest version。I try enable filter,
```
    <entry key='filter.enable'>true</entry>
    <entry key='filter.duplicate'>true</entry>
```
Sending duplicate data，The following error occurred
```
2018-06-30 10:13:22  INFO: [78115942] connected
2018-06-30 10:13:26 DEBUG: [78115942:5013 < 192.168.1.6] HEX: 2461706634580138263006183305421906116236258e000000ffff9fff000000000000000001cc0056d67e5535
2018-06-30 10:13:27  INFO: Position filtered by Duplicate filters from device: 6170663458
2018-06-30 10:13:27  WARN: [78115942] error - msg - NullPointerException (... < BaseDataHandler:27 < ... < *:27 < ... < *:27 < ... < ExtendedObjectDecoder:64 < ... < WrapperContext:102 < ...)
2018-06-30 10:13:27  INFO: [78115942] disconnected
```

**Comment by tananaev** [comment] 2018-07-01 18:14
The issue is fixed now.

**Closed** 2018-07-01 18:14 UTC

**Comment by gpsim** [comment] 2018-07-02 01:08
Thank you， tananaev！
