### ISSUE TITLE
demo3 no working on my account

### ISSUE THREAD

**Issue by m4niek** [traccar/traccar#2000] opened 2016-06-04 13:47 UTC
hi,
I have problem with my account,
2h is loading data - picture (that same problem on the chrome or edge and mozilla)
what is problem?
thanks
![demo3](https://cloud.githubusercontent.com/assets/19748377/15799874/99453f3c-2a6b-11e6-8248-0069b87130e6.jpg)

**Comment by tananaev** [comment] 2016-06-05 01:14
I have restarted the service. Please check if the issue is solved.

**Comment by m4niek** [comment] 2016-06-05 05:14
hello Anton, thanks for the reply, is still not working. If I want to open the data for the new account I have information that the device already exists in the database. "Duplicate entry 'CW9999C...x.....x..' for key 'uk_device_uniqueid' - MySQLIntegrityConstraintViolationException (... < QueryBuilder:431 < DataManager:345 < DeviceResource:59 < ...)". 
it may be better to remove the account along with the data devices? send you email updates data logging and device numbers?

**Comment by tananaev** [comment] 2016-06-05 06:29
What's the account id? Can I reset the password to take a look? Or you can send me full login details if you prefer.

**Comment by m4niek** [comment] 2016-06-05 06:39
hello,
I sent an email from support page

**Comment by tananaev** [comment] 2016-06-05 07:09
Please try again now.

**Comment by m4niek** [comment] 2016-06-05 09:44
still not work, my login detektywi@op.pl for http://demo3.traccar.org/, reset password - ok

**Comment by m4niek** [comment] 2016-06-05 09:50
I added a new device, despite loading the data, after a moment unlocks, thank

**Comment by m4niek** [comment] 2016-06-05 09:52
All functions work, once again thank you

**Comment by m4niek** [comment] 2016-06-05 09:59
monologue :)
Again the same problem. Loading.....

**Comment by tananaev** [comment] 2016-06-05 11:01
The problem is with deleting devices. Don't delete devices.

**Comment by m4niek** [comment] 2016-06-05 11:32
thanks, service working,
or at a later date, you can remove the device?

**Comment by tananaev** [comment] 2016-06-05 13:48
I think there is a constraint missing in the database for some reason, so removing device doesn't actually remove the link between user and device, so link becomes invalid as device record doesn't exist anymore. I'll investigate this problem more, but for now you should avoid removing devices.

**Comment by m4niek** [comment] 2016-06-18 06:37
Hello,
1
Please write me if the problem is solved?
if you can already remove unnecessary device?
2
CCTR600 device does not indicate the GPS position information is new data - the color green, the device function properly, CCTR working properly and indicates the position where it sends an SMS or a link to your phone, if the problem is on the side of the device or server?

**Comment by tananaev** [comment] 2016-06-18 06:41
1. I fixed is a long time ago... when I made a comment.

2. What's the device id?

**Comment by m4niek** [comment] 2016-06-18 06:45
wow - quick response
ID Device CW9999C00000538

**Comment by m4niek** [comment] 2016-06-18 07:48
hm...
![loading](https://cloud.githubusercontent.com/assets/19748377/16169748/b919ac66-3539-11e6-8932-ada3d86c6d7c.jpg)

Again the same problem. Loading data

**Comment by tananaev** [comment] 2016-06-19 09:32
You removed a bunch of devices again.

**Comment by tananaev** [comment] 2016-06-19 09:33
Fixed for now, but as I said, you shouldn't remove devices because it's going to break you account.

**Comment by m4niek** [comment] 2016-06-19 11:07
thanks,
please tell me what is problem - ID Device CW9999C00000538

**Comment by tananaev** [comment] 2016-06-19 12:19
I can see data from your device, but the format is slightly different from currently implemented protocol. I need protocol documentation from device manufacturer to adjust the decoder.

**Comment by m4niek** [comment] 2016-06-21 13:38
I do not have the manual for administrator, in Annex user manual, if I can help it I'm waiting for information

[CCTR600.pdf.zip](https://github.com/tananaev/traccar/files/325678/CCTR600.pdf.zip)

**Comment by tananaev** [comment] 2016-06-21 22:01
It doesn't really help. I still need protocol documentation.

**Comment by m4niek** [comment] 2016-07-11 10:19
Hi again,
Today about 2 hours ago I noticed the lack of visible devices in the panel (5 devices)
trying to add an error message appears - the devices are already in the database,
please support in this matter

**Comment by tananaev** [comment] 2016-07-11 11:13
Please try again. There are some minor stability issues with demo servers after update.

**Comment by m4niek** [comment] 2016-07-11 15:20
still not work

![traccar error](https://cloud.githubusercontent.com/assets/19748377/16736014/8a79c5ee-478b-11e6-8e5c-a700ed1be0ae.jpg)

**Comment by tananaev** [comment] 2016-07-11 22:02
Fixed one problem. Please try again now.

**Comment by m4niek** [comment] 2016-07-12 07:54
hmmm, still not work

**Comment by tananaev** [comment] 2016-07-12 08:06
What's you user and device ids?

**Comment by m4niek** [comment] 2016-07-12 08:36
login detektywi@op.pl pass 123456

**Comment by m4niek** [comment] 2016-07-12 08:39
357566040017344 Test 344 TheBest of 3

357566040017997 Test 997 LowFix

357566040017690 Test 690 PowerB

CW9999C00000538 CCTR600

357749036906452 GC101

**Comment by tananaev** [comment] 2016-07-12 10:35
I can see the devices:
![screen shot 2016-07-12 at 10 34 30 pm](https://cloud.githubusercontent.com/assets/1161863/16764190/d6ab2296-4880-11e6-928b-df6462a49021.png)

**Comment by m4niek** [comment] 2016-07-12 16:02
if you want further help?
me does not work: mozilla, chrome, opera, torbrowser, traccar app for android
not work: mozilla, chrome for win10
below photos,
maybe the problem is in the PL version or ip for Poland?


![20160712_174451](https://cloud.githubusercontent.com/assets/19748377/16773908/078d16ca-485a-11e6-830f-64c19587b66e.jpg)
![20160712_174500](https://cloud.githubusercontent.com/assets/19748377/16773910/07909566-485a-11e6-9f52-95a495b1cf47.jpg)
![20160712_174629](https://cloud.githubusercontent.com/assets/19748377/16773913/0797f81a-485a-11e6-96ae-144dae3f3d64.jpg)

**Comment by tananaev** [comment] 2016-07-12 22:33
I would recommend to check browser developer console (e.g. in desktop Chrome). See if there are any errors or warnings there. There must be some problem with API calls.

**Comment by m4niek** [comment] 2016-07-13 06:05
console problem is:
http://demo3.traccar.org/api/session?_dc=1468389476284 Failed to load resource: the server responded with a status of 404 (Not Found)
http://demo3.traccar.org/fake-login.html Failed to load resource: the server responded with a status of 404 (Not Found)
http://demo3.traccar.org/api/devices?_dc=1468389479462&page=1&start=0&limit=25 Failed to load resource: the server responded with a status of 400 (Bad Request)

![traccar chrome](https://cloud.githubusercontent.com/assets/19748377/16793313/528c505c-48d0-11e6-90be-ec3c5d6336b7.jpg)

**Comment by tananaev** [comment] 2016-07-13 06:20
Try to open this link (make sure you are logged in first):

http://demo3.traccar.org/api/devices

**Comment by m4niek** [comment] 2016-07-13 06:28
{"message":null,"details":"NullPointerException"}

**Comment by tananaev** [comment] 2016-07-13 22:10
Please try now.

**Comment by m4niek** [comment] 2016-07-14 13:00
bad thing, d'not work (app traccar, chrome, mozilla android and win10):
http://demo3.traccar.org/api/session?_dc=1468500721593 Failed to load resource: the server responded with a status of 404 (Not Found)
http://demo3.traccar.org/fake-login.html Failed to load resource: the server responded with a status of 404 (Not Found)
http://demo3.traccar.org/api/devices?_dc=1468500724810&page=1&start=0&limit=25 Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by m4niek** [comment] 2016-07-14 13:01
can delete my account from the device and the base, I create a new - does not need a story?

**Comment by m4niek** [comment] 2016-07-14 13:04
Copy this does not solve the problem. I have a new account and you can not add new devices, the problem of compulsion to be somewhere else:
"NullPointerException (GeofenceManager:278 < DataManager:162 < *:390 < DeviceResource:60 < ...)"

**Comment by tananaev** [comment] 2016-07-14 13:11
I don't know what's happening with your accounts. Everything works fine for me.

Have you created any groups/geofences or anything else? Or just devices?

**Comment by m4niek** [comment] 2016-07-14 13:33
it was all in accordance with the instructions, no groups/geofences, no additional setup, the server runs for several more weeks, one morning I saw the equipment and do not see them today, I believe that the problem is not on my side, not even work your app, the new account I can not add devices, etc

how can I have given you a public username and password, someone did joke

**Comment by tananaev** [comment] 2016-07-14 22:07
If you want send me details by email (address is in profile).

**Comment by tananaev** [comment] 2016-07-16 00:30
Please try again now. I did some cleanup in the database.

**Closed** 2022-06-26 13:48 UTC
