### ISSUE TITLE
Spaces in name fails on forward.url

### ISSUE THREAD

**Issue by leifnel** [traccar/traccar#4008] opened 2018-08-13 11:02 UTC
When a device name have spaces, forward.url fails.

` WARN: [2bada3f4] error - java.net.URISyntaxException: Illegal character in query at index 54: https://server.my,dom:1880/rest/traccar/pos?name=Jane Doe&deviceTime=1534156975000&fixTime=1534156975000&valid=true&course=308.6380920410156&speed=6.932212151679993&lat=46.453767&lon=9.046107&alt=-2.596615267672284&status=0xF11C - UriBuilderException (... < WebDataHandler:135 < BaseDataHandler:27 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < ExtendedObjectDecoder:64 < ...)
`

The spaces need url-escaping

**Comment by tananaev** [comment] 2018-08-13 11:29
Duplicate of #3995, which is already fixed.

**Closed by tananaev** 2018-08-13 11:29 UTC
