### ISSUE TITLE
lairdtech lt100

### ISSUE THREAD

**Issue by ftrindad** [traccar/traccar#4303] opened 2019-05-02 13:32 UTC
Good Morning.
I installed the tracing system on a wibndows server and I am performing tests, the system seems to work perfectly, but I use a lairdtech equipment, the model is lt100. I do not have the protocol of this equipment, but using GT02 it recognizes the ID and shows it as connected, but does not receive any further information.
down the log data.
```
2019-05-02 10:26:24 INFO: [35438fd3: gt02 <187.60.53.238] HEX: 363336323536303930303037342c422c2c000501000b50513d0a152833191a3c1e000000d104000000003e0f33ffc37281fe000000000000008474000000
```
Thanks for the help.

**Comment by tananaev** [comment] 2019-05-02 15:12
It's definitely not GT02 protocol.

**Comment by tananaev** [comment] 2019-05-02 15:58
Duplicate of the forum thread:

https://www.traccar.org/forums/topic/lairdtech-lt100/

**Closed by tananaev** 2019-05-02 15:58 UTC
