### ISSUE TITLE
Feature Request: User Permissions

### ISSUE THREAD

**Issue by nblracer880** [traccar/traccar#4041] opened 2018-09-03 23:37 UTC
First off, I am enjoying this software, thank you!!

It would be awesome if a regular user weren't able to edit their own attributes. I realize that the user attributes really aren't for controlling permissions. But there are features that I would like to block certain users from using.

Is there a possibility that more advanced permissions control could be implemented in the future?

Thanks!!

**Comment by tananaev** [comment] 2018-09-03 23:39
Well, you need to explain your use case first. Then we see if anyone else is interested. And if yes, we will consider implementing it.

**Comment by nblracer880** [comment] 2018-09-03 23:43
I'd like to block certain users from accessing features like reports, maintenances, geofences, notifications, etc.

For now, I have just been disabling the features in the user's attributes, but if they are clever, they can go in and enable the features without administrator approval.

**Comment by tananaev** [comment] 2018-09-03 23:50
By explaining the case I meant the business case for this requirement.

**Comment by nblracer880** [comment] 2018-09-03 23:53
Oh OK, sorry.

We will be selling monitoring services. Different levels of services will have different features available to the client. The features that will change based on service plan are; reports, maintenance's, notifications, etc.

**Comment by tananaev** [comment] 2018-09-04 00:08
OK, let's wait and see how much interested is there for this feature.

**Comment by nblracer880** [comment] 2018-09-04 00:09
Thanks so much!!

**Comment by PiotrIT** [comment] 2018-09-24 11:50
I'm interested this feature too.

**Comment by victorferreira** [comment] 2018-11-05 11:36
I'm also interested in this feature. I have implemented an app outside of traccar to control with features a user has access to and would be nice not to maintain two applications.

**Comment by ali-raza101** [comment] 2018-11-15 09:49
@tananaev There is a business case in which,"A simple user" can access saved commands to Stop/Resume Engine. The problem is Read-only user cannot send commands and normal user can with additional access to delete his device. Now many customers delete their devices from their account 
 or delete notifications deliberately and then call company's support about missing device. 

So it would be very useful when admins can set permissions of a user role to "Readonly" but also can give access specifically to "Saved commands". 

By this way we can restrict users to monitor their vehicles 24/7 and also can control Engine Kill command, without disturbing any other account setting.

**Comment by tananaev** [comment] 2018-11-15 10:45
@ali-raza101, have you checked "device readonly" option?

**Comment by ali-raza101** [comment] 2019-02-20 08:33
@tananaev  have you understood the case and the requirement? I've tried to described the business case above, please have a look at the following table to get the idea what feature we are demanding in this thread. 

![2019-02-20 13_16_45-traccar user types - excel](https://user-images.githubusercontent.com/41426824/53076947-bdb5c300-3512-11e9-82e8-dfaac54700d9.png)


Here we all want this last permission as I've mentioned in this table as "Readonly + AllowCommands".

**Just for example sake name this user-type as "Controlled-User", now this user can:**
- View his devices added in his account by admin _(just like read-only user)_
- Can also send commands like 'Engine stop/Start" in case of unauthorized usage _(due to new Allow-Commands Permission)_
- Finally Controlled User cannot mess up (modify) the Notifications, GeoFence and account settings created by Admin/Manager  _(just like read-only user)_

Hoping your kind response. 🙂

**Comment by tananaev** [comment] 2019-02-20 16:37
I understand the requirement, but you are not really explaining the business case here.

**Comment by ali-raza101** [comment] 2019-02-21 21:54
Ok, let me explain. Here is the business case which I see after visiting many tracking companies and analyzed their services.

Imagine yourself a Vehicle Tracking Service Providing Company, you offer **different Pricing Packages** to your customers. Now your customers pay you according to the features. For discussion sake, take a look at following pricing packages as an example:

![github 2](https://user-images.githubusercontent.com/41426824/53204007-6f0c4400-364c-11e9-92f7-cf583c357a9e.png)

Now as we can see that in higher packages there are more options, which ultimatley also have higher costs at backend for company, for example:

- In Gold package customer gets SMS-notifications on important alerts and even on ignition on/off
- One sms using SMPP service provider gateway costs around $0.10
- Based on 3 trips daily, a vehicle can generate upto 90 sms per month and 1080 sms per year which costs around **$108 only on ignition on/off alone**
- If the company uses traccar, and set user permission other than Device_Read_Only then **currently their CUSTOMERS (i.e. users) having silver package can also create/delete notifications from their account settings themselves**, by this way company can face huge costs or I would say **LOSS on due to such customers**
- And if company totally restricts **user as READ-ONLY then the customer himself cannot kill engine** in case of unauthorized usage which is a very important and essential feature.

The only possibility to overcome both of the above problems, is **by Creating another Additional Permission on Read-Only user, allowing them to send commands.**
By this way **users can send commands** to their devices like Engine Kill, and **secondly they cannot manipulate or change notifications/geofence settings** which are created by Admins according to their Pricing Package at the time of purchasing the service.

**Comment by ali-raza101** [comment] 2019-02-21 21:55
@tananaev Ok, let me explain. Here is the business case which I see after visiting many tracking companies and analyzed their services.

Imagine yourself a Vehicle Tracking Service Providing Company, you offer **different Pricing Packages** to your customers. Now your customers pay you according to the features. For discussion sake, take a look at following pricing packages as an example:

![github 2](https://user-images.githubusercontent.com/41426824/53204007-6f0c4400-364c-11e9-92f7-cf583c357a9e.png)

Now as we can see that in higher packages there are more options, which ultimatley also have higher costs at backend for company, for example:

- In Gold package customer gets SMS-notifications on important alerts and even on ignition on/off
- One sms using SMPP service provider gateway costs around $0.10
- Based on 3 trips daily, a vehicle can generate upto 90 sms per month and 1080 sms per year which costs around **$108 only on ignition on/off alone**
- If the company uses traccar, and set user permission other than Device_Read_Only then **currently their CUSTOMERS (i.e. users) having silver package can also create/delete notifications from their account settings themselves**, by this way company can face huge costs or I would say **LOSS on due to such customers**
- And if company totally restricts **user as READ-ONLY then the customer himself cannot kill engine** in case of unauthorized usage which is a very important and essential feature.

The only possibility to overcome both of the above problems, is **by Creating another Additional Permission on Read-Only user, allowing them to send commands.**
By this way **users can send commands** to their devices like Engine Kill, and **secondly they cannot manipulate or change notifications/geofence settings** which are created by Admins according to their Pricing Package at the time of purchasing the service.

**Comment by ali-raza101** [comment] 2019-03-02 04:00
@tananaev does this example clarifies the business case now? If yes then can we expect this permission in next traccar release?

**Comment by tananaev** [comment] 2019-03-02 05:26
Yes, it does clarify it. Unlikely in the next release, but possibly in one of the future releases.

**Comment by ali-raza101** [comment] 2019-03-07 15:09
@tananaev Sir we will be waiting for that release  😊  Thanks a lot.

**Comment by ali-raza101** [comment] 2019-04-26 19:55
@tananaev any luck for us of this feature in next release? :confused:

**Comment by tananaev** [comment] 2019-04-26 20:01
I will comment here if there is an update.

**Comment by ali-raza101** [comment] 2020-02-03 15:14
@tananaev it's been 8 months now, any luck?

**Comment by ali-raza101** [comment] 2020-02-26 11:23
@tananaev sir any updates, when we can expect this feature?

**Comment by tananaev** [comment] 2020-02-26 16:58
@ali-raza101 is there something not clear about my last comment?

> I will comment here if there is an update.

**Comment by ali-raza101** [comment] 2020-03-05 05:55
> @ali-raza101 is there something not clear about my last comment?
> 
> > I will comment here if there is an update.

Everything was clear but @tananaev have you seen when did you commented last, it was on "Apr 27, 2019". So I think it is fair to ask again as a reminder after more than 10 months.

**Comment by ali-raza101** [comment] 2020-10-09 16:26
@tananaev would you mind to give any idea when this will be included in traccar official release. 
As it is a business case that's why people are demanding this feature, like here https://www.traccar.org/forums/topic/command-and-notifications-button-gone-for-read-only-users-in-ver-3-10/#post-56329
and here
https://www.traccar.org/forums/topic/read-only-user-with-send-saved-commands/

Hoping for your positive response

**Comment by tananaev** [comment] 2020-10-09 16:59
I can't provide any dates.

**Comment by ali-raza101** [comment] 2020-11-05 00:25
Hi Anton @tananaev I've consulted some of my friends circle who are developers, they are ready to help us out in their spare time from job. Can you please guide us exactly which files needs changes to modify **Permissions for Read-only user** so that such user will be able to **Send-Commands** as explained in above comments. Your help would be really appreciated.  Thanks

**Comment by tananaev** [comment] 2020-11-05 00:40
I cannot guide you which exact files need to be modified, but you should be able to find relevant classes if you search for "readonly" property in the code.

**Comment by ali-raza101** [comment] 2020-11-20 23:07
That would need a deep code change which requires professional skills, certainly I'm not a pro. @tananaev  As you can see this is a business case requirement by several of traccar users. Can you please tell, if you have discuss this with your team and **when we can expect this feature in official traccar release?**
Stay blessed and thumbs up for this great project. 🙂

**Comment by tananaev** [comment] 2020-11-20 23:27
OK, I want to clarify something. We don't provide estimates for features. It can be months or it can be years. Please don't ask for dates. If I have some specific plans or dates I will share it.

If this feature is so important and urgent for you, you can always sponsor the work. In that case we can provide you the timeline and cost estimate. If you or someone else is interested in sponsoring this or some other feature, please contact me by email.

**Comment by ali-raza101** [comment] 2020-11-25 15:35
> OK, I want to clarify something. We don't provide estimates for features. It can be months or it can be years. Please don't ask for dates. If I have some specific plans or dates I will share it.
> 
> If this feature is so important and urgent for you, you can always sponsor the work. In that case we can provide you the timeline and cost estimate. If you or someone else is interested in sponsoring this or some other feature, please contact me by email.

First of all this is not a feature from scratch to built, its a modification of the existing user roles/permissions.
However, we understand you may have your own plans and timelines so let's discuss if we can afford this for public interest. Please share your email address.

**Comment by tananaev** [comment] 2020-11-25 15:38
It's in the profile.

**Comment by tananaev** [comment] 2022-07-16 01:46
Added an option to hide attributes for regular users - https://github.com/traccar/traccar-web/commit/85a3576f3046f5bcf3bbac6ad952ef180762fd51.

**Closed by tananaev** 2022-07-16 01:46 UTC
