### ISSUE TITLE
Feature Request : API Updates - Update values of field only if field defined in the query

### ISSUE THREAD

**Issue by jaimzj** [traccar/traccar#3873] opened 2018-05-08 20:31 UTC
The feature request is for a condition to be put in API requests' where if a field is not explicitly defined in the update query, the field should not be updated nor modified and it should remain at its original state.

And only fields that are submitted in the query should be updated.

Reason :

At present Updating any Object requires that all fields are posted along with its last known value or new updated value. 

Not defining a field value or missing out on posting a field, updates the value of the field to null in the current scenario.

However to avoid unplanned or unnecessary updates to fields. specially fields in device API such as 'geofenceIds, lastUpdate, status, positionId' which are handled by traccar back-end.

**Comment by VanitySoft** [comment] 2018-05-08 20:37
Sounds like a bug more than a feature?

Jeryl Cook
Founder & Chief Executive Officer
VanitySoft, Inc.
A Geo Business Intelligence Technology Consulting Firm
www.vanity-soft.com
www.linkedin.com/in/jerylcook
Get answers to "who knew what, when, and where"... and everything in
between.

**Comment by tananaev** [comment] 2018-05-08 20:40
It's not a bug.

**Comment by gpshex007** [comment] 2020-03-09 15:29
@tananaev is this something you would consider implementing? Mainly & Specially for devices

We use API to communicate with Traccar and it is an issue while editing and updating a device specially when the device is constantly getting real time updates and we need to send the positionId even though we are just updating the device name etc.

Would appreciate your feedback or any help in this matter.

**Comment by tananaev** [comment] 2020-03-09 16:44
You don't need to send `positionId` or `status`.

**Comment by gpshex007** [comment] 2020-03-09 17:02
Thank you for the response @tananaev truly appreciate it.

**Comment by tananaev** [comment] 2022-07-12 16:33
I'm pretty sure fields geofenceIds, lastUpdate, status, positionId are ignored. So you don't need to send them and it's going to work just fine.

I'm going to close this for now because I don't think we would be making any big changes like this to the APIs.

**Closed by tananaev** 2022-07-12 16:33 UTC
