### ISSUE TITLE
Since upgrading to 5.11, Multiple notifications are being sent for a single event

### ISSUE THREAD

**Issue by ingestre** [traccar/traccar#5250] opened 2024-01-17 12:19 UTC
**Describe the bug**
Since upgrading to 5.11, Multiple (3-4?) notifications are being sent for a single event.
The multiple notifications go to all users who have that notification assigned.
Downgrading to 5.10 fixes the problem

**To Reproduce**
I am not using groups. I just assign the notification to the device and the user.
The notification is an email notification
The notification in question does not have "All devices" checked.

**Expected behavior**
Each event should only spawn 1 notification to each appropriate user. Not the 3-4 currently being observed

**Screenshots**

**Server**
Raspberry Pi running raspbian (bullseye)
MySQL database running on same server as app

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
I downgraded to the previous version (5.10) and the problem went away.

**Comment by tananaev** [comment] 2024-01-17 14:15
Duplicate of https://github.com/traccar/traccar/issues/5245.

**Closed by tananaev** 2024-01-17 14:15 UTC
