### ISSUE TITLE
Watch Protocol: error - scheme - NullPointerException

### ISSUE THREAD

**Issue by pbreah** [traccar/traccar#3836] opened 2018-04-06 20:25 UTC
I have the following setup on my Traccar instance:

Traccar: **3.16**
Protocol: **watch**
Port Used: **5093**

**Symptoms**:
The Q50 watch is not registering with Traccar properly and is returning an error.
 
**Error message**:
```
2018-04-06 18:08:42 DEBUG: [C5566D6C: 5093 > 172.24.0.1] HEX: 5b33472a363130393339353338312a303030322a4c4b5d
2018-04-06 18:08:42  WARN: [C5566D6C] error - scheme - NullPointerException (... < EventForwarder:52 < NotificationManager:105 < *:111 < ConnectionManager:109 < ...)
```

Probably the protocol needs an update.

**Comment by pbreah** [comment] 2018-04-06 20:57
I sent you a protocol document I have via email.

**Comment by tananaev** [comment] 2018-04-06 21:10
Duplicate of forum thread:

https://www.traccar.org/forums/topic/connecting-gps-watch-to-server/

**Closed by tananaev** 2018-04-06 21:10 UTC
