### ISSUE TITLE
Odometer units

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar#2233] opened 2016-08-21 05:53 UTC
I'll try to collect here an information about odometer (`KEY_ODOMETER`) units
- [x] Mta6 - kilometers
- [x] Xirgo - "Miles driven since last reset or power-cycle"
- [ ] Gps103 - **?**
- [x] Intellitrac - get from OBD
- [x] GL200 - miliage  0.0 – 4294967.0 km
- [x] Tytan - Distance travelled from switching ignition on and switching it off, calculated from GPS position (0-16777215m)
- [x] T800x - Mileage (Meter) 0~4294967295
- [x] GT06 - **?** mileage statistics (hexadecimal), real is meters
- [x] Megastek - Mileage, unit: Km
- [x] Tzone - GPS  mileage(3bytes)：Unit：m
- [x] Meitrack - In unit of meter. Decimal. The total accumulated mileage and maximum of 4294967295 meters.
- [x] Ulbotech - Mileage data Range: 0‐4294967295 unit: meter
- [ ] Fox - **no documentation**
- [ ] Stl060 - **?**
- [x] Visiontek - km
- [x] Totem - Km in format that has documentation, **?** integer in `PATTERN3` and `PATTERN4` that **does not have documenatation** but 7 digits looks like km
- [x] Tk103 - Mile data. Unit: Meter. The total mileage. The max is 0xFFFFFFFF
- [ ] Progress - **?** mileage INT32U
- [x] Navis - float mileage in km, also next parameter should be renamed to `KEY_DISTANCE`

> Пробег, рассчитанный между данным событием и предыдущим. (между двумя точками трека) В км.
- [ ] Noran - **no documentation for protocol version that has odometer**
- [x] Meiligao - no direct information in documentation, but indirect it is in meters.
- [ ] Mxt - **no documentation**
- [x] Jt600 - Current mileage, in the unit of kilometer
- [x] Castel - Total mileage, unit: meter
- [x] CarTrack - meters
- [x] Wondex - kilometers
- [x] Taip - meters
- [ ] Supermate - **no documentation**
- [x] Skypatrol - meters
- [x] Pt502 - **no documentation** but looks like meters
- [x] Riti - "Total Mileage(4 bytes, LSB - MSB) Total moving distance, refreshes the calculations when ACC is ON at each time. Unit: meter"
  Also need to use `KEY_DISTANCE` for previous parameter: "Moving distance, calculates the distance between current data, and latest previous data. Unit: meter"
- [x] Mtx - "Distancia recorrida (en kilómetros)"
- [ ] L100 - **no documentation** 
- [x] Khd - meters, max 16777215
- [x] HuaSheng - weird km/h
- [x] GoSafe - meters
- [x] Gator - Quote from both documents: "The current mileage of the vehicle.unit:m/s"
  My knowledge of physics tells me that it should be meters
- [x] Galileo - meters
- [ ] Flextrack - **no documentation**
- [x] EasyTrack - km, need correction to 0,1
- [x] Disha - **?**  **no documentation** looks like floating-point kilometers
- [x] Carscop - meters
- [x] Box - does not fits by default "By default this contains the distance travelled since the start of the journey (travel). This can be configured to return the odometer reading if required. Distance is returned as a floating point number in Kilometers."
- [ ] Bce - **?**  **no information in documentation**
- [x] Atrack - **no documentation** looks like 0,1 kilometers
- [x] Astra - "The odometerKM field in the EventData table is populated with data from the device for ignition on and ignition off records. For all other records it is reported as zero."
  I'll convert it to meters, but it is useless.
- [ ] Aquila - **no documentation**
- [x] Apel - meters
- [x] Adm - meters

I think protocols that get odometer from OBD leave it as is, and it will be kilometers or miles depend on country.

**Comment by tananaev** [comment] 2016-08-21 09:24
GitHub supports checkboxes in the issues. It should help to track what's done from the list.

**Comment by Abyss777** [comment] 2016-08-22 08:31
I've analyzed one third of protocols and already do not like idea to use `KEY_ODOMETER` to calculate distance for reports.
It can be everything. Distance between ignition on/off. For GL200 I guess it is distance between positions, because it is only two bytes of meters. 
Also I think values in meters just calculated from GPS but internally in device. I guess they do not have much difference from calculated in traccar. I even think that precise can be less.

I think only useful distance is got "from tires" that mostly can be received via OBD.
If we decide to use `KEY_OBD_ODOMETER` we have to find way to know km or miles it is.
I suggest to store it in device/group/server attributes.

@tananaev what do you think?

**Comment by tananaev** [comment] 2016-08-22 08:37
Distance calculated on the device should be more precise than on the server because device can calculate it every second (GPS usually reports location every second). For protocols that don't return accumulated odometer, we can just change attribute key to something else and ignore those.

**Comment by Abyss777** [comment] 2016-08-22 08:50
OK.
And if mileage is not in meters we will convert it to meters on protocol side?

**Comment by tananaev** [comment] 2016-08-22 08:51
Yes, correct.

**Comment by Abyss777** [comment] 2016-08-22 11:29
Fuf, finished analyzing.

Statistic:
- 15 protocols stores in meters, 4 of them can't be used because resets every trip (ignition on/off) or too small (GL200)
- 9 need conversion to meters
- rest does not have documentation or there is no information about units

What is better? parameters that is not good rename to something else or parameters that fit rename to something like`KEY_MILEAGE` and use them in `calculateDistance` ?

**Comment by tananaev** [comment] 2016-08-22 12:18
Parameters that are for the trips, can be renamed to `KEY_TRIP` or `KEY_TRIP_ODOMETER` or something like that.

**Comment by Abyss777** [comment] 2016-08-24 12:24
@tananaev  You implemented HuaSheng recently. Do you remember what is `KEY_ODOMETER` there?
According to manual it is:

> Mileage collection: device can collect GPS speed and meter speed to calculate interval mileage and send to platform. Platform works out total mileage according to interval mileages.

Looks like distance, not accumulated odometer.

**Comment by Abyss777** [comment] 2016-08-24 12:33
@nefertiti007 as I understand you have GT06 devices.
Could you check what is in "odometer" attribute? meters/kilometers or miles? Is it accumulated or reseted every trip?
Documentation does not explain what is it
> mileage statistics (hexadecimal)

Thank you.

**Comment by nefertiti007** [comment] 2016-08-24 15:15
@Abyss777 As per the data I have,.

The "odometer" attribute for GT06 is in meters. And Its accumulated and not reset every trip.

I have asked the manufacturer as well,. They haven't yet confirmed but 99% what I shared above is correct as per my understanding,. and Data I have,.

**Comment by nefertiti007** [comment] 2016-08-24 15:53
I have updated the post above based on manufacturers response @Abyss777

**Comment by tananaev** [comment] 2016-08-24 16:11
@Abyss777, it's funny. HuaSheng documentation says:
> Odometer speed, unit: km/h

I have uploaded the document here if you want to take a look:

https://www.traccar.org/protocols/

**Comment by Abyss777** [comment] 2016-08-24 16:55
@nefertiti007 thank you very much

@tananaev  what we will do with HuaSheng? Assume it is kilometers? Do you have real packets examples? Also what we will do with GT06? I suggest base on real @nefertiti007 feedback and use meters. Also it is **unsigned int**, I do not think it can be 4 294 967 295 kilometers.

**Comment by tananaev** [comment] 2016-08-24 17:02
Let's assume that HuaSheng is in KM. I don't have any example other than what's in the tests.

GT06 should be in KM, right?

**Comment by Abyss777** [comment] 2016-08-24 17:09
No, I think GT06 should be meters.

**Comment by tananaev** [comment] 2016-08-24 17:11
@nefertiti007 says that it's in km.

**Comment by nefertiti007** [comment] 2016-08-24 17:13
@tananaev  & @Abyss777 , If you can tell me one thing,. I might be able to confirm or share more valuable data.

For example in GT06 devices attributes in traccar position table, I see 
odometer=796119  (For 4 days,. ) so this odometer value shown, in traccar attributes, is traccar already converting the value from km to mtrs? if not then device is sending mtrs right?

**Comment by tananaev** [comment] 2016-08-24 17:16
It doesn't convert anything at the moment, so it must be in meters.

**Comment by Abyss777** [comment] 2016-08-24 17:18
@nefertiti007 for now traccar do not convert GT06 odometer value, and it looks like meters.

**Comment by nefertiti007** [comment] 2016-08-24 17:18
In that case, Yes, @tananaev I also feel its meters for GT06, because for a device I activated the odometer just few days back,. and it shows odometer = 796119 (So this value cant be kilometer), You are right. so its meters. and just to confirm this i calculated for those number of days distance between each position entry = and as per my report vehicle as traveled at-least 740km+

**Comment by TechCh** [comment] 2018-08-09 08:05
@jaimzj Please share me the details to activate the odometer function in GT06N GPS device.
Vaue's i receving without odometer data. Help me to solve that issue.

**Comment by tananaev** [comment] 2022-06-23 15:08
I think we can close this for now. If some odometer values are not decoded correctly, we can solve them one by one.

**Closed by tananaev** 2022-06-23 15:08 UTC
