### ISSUE TITLE
Incorrect syntax near 'LIMIT'. - SQLServerException

### ISSUE THREAD

**Issue by rburwood** [traccar/traccar#4972] opened 2022-10-28 00:14 UTC
**Describe the bug**
When using MS SQL Server as the DB Server, When using the Traccar Android Client (possibly others aswell) the client is unable to update the system. I get the following error in the logs:
`INFO: [T6adbae8b] error - Incorrect syntax near 'LIMIT'. - SQLServerException (... < QueryBuilder:417 < DatabaseStorage:71 < CommandsManager:102 < ...)`

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Traccar traccar-windows-64-5.4 with MS SQL Server 2019
2. Install Traccar Android Client App
3. Add device in Management UI
4. Device is unable to update the system

**Expected behaviour**
The system to run without issue on MS SQL Server

**Additional context**
MS SQL Server doesn't support "LIMIT". The MS SQL query syntax should use "TOP" - The query builder should adjust the query based on the target db server.

**Comment by tananaev** [comment] 2022-10-28 00:19
Duplicate of #4958.

**Closed by tananaev** 2022-10-28 00:19 UTC

**Comment by rburwood** [comment] 2022-10-28 00:43
Great that this is fixed. When do you intend on rebuilding the installers?

**Comment by tananaev** [comment] 2022-10-28 00:46
Don't have dates yet.
