### ISSUE TITLE
OIDC accounts do not get Notification Tokens populated. Breaks traccar push notifications.

### ISSUE THREAD

**Issue by Sleuth56** [traccar/traccar#5400] opened 2024-08-30 21:16 UTC
**Describe the bug**
When creating an account with OIDC the account does not get the Notification Token added to the account attributes. This breaks traccar push notifications and probably other notification backends as well.

**To Reproduce**
1. Create an OIDC user
3. Click on account, account
4. Expand attributes.
5. See that Notification Tokens doesn't exist.
---
1. Click on notifications
2. Click on +
3. Pick a type (doesn't matter)
4. Click on Channel and select Traccar(Probably effects other backends as well)
5. Click Test Channels
6. Nothing shows up on your device

**Expected behavior**
When logging in with OIDC for the Notification Tokens Account Attribute to be created and push notifications to work.

**Smartphone (please complete the following information):**
 - Device: Pixel 7a
 - OS: Android 14
 - Browser traccar-manager app from google play
 - Version 4.4

**Comment by tananaev** [comment] 2024-08-30 21:48
Duplicate of https://github.com/traccar/traccar-web/issues/1259.

**Closed by tananaev** 2024-08-30 21:48 UTC
