### ISSUE TITLE
Build instructions (Maven to Gradle migration)

### ISSUE THREAD

**Issue by alexthefifth** [traccar/traccar#4491] opened 2020-02-25 18:11 UTC
The build instructions page says "Traccar is a Maven project" ... " To generate binary files execute "mvn package" command in the terminal."

https://www.traccar.org/build/

But it seems that as of 4.4 you've migrated to Gradle:

https://www.traccar.org/blog/traccar-4-4/

"Migrated project from Maven to Gradle, which is a more modern build system"

if anyone was as confused as me: the Gradle equivalent of "mvn package" is "./gradlew build"

**Comment by tananaev** [comment] 2020-02-25 18:13
Duplicate of #4490.

**Closed by tananaev** 2020-02-25 18:13 UTC
