### ISSUE TITLE
Java startup error with current docker alpine image

### ISSUE THREAD

**Issue by cybermcm** [traccar/traccar#4688] opened 2021-06-03 05:24 UTC
**Describe the bug**
Current apline docker image (sha256:0ab3bb4d69b89de3834ac1a472fea07a16f5fdc28ea8902ebb0c26885e7279bb) startup error
```
traccar                     | Error: A JNI error has occurred, please check your installation and try again
traccar                     | Exception in thread "main" java.lang.UnsupportedClassVersionError: org/traccar/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
traccar                     |   at java.lang.ClassLoader.defineClass1(Native Method)
traccar                     |   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
traccar                     |   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
traccar                     |   at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
traccar                     |   at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
traccar                     |   at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
traccar                     |   at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
traccar                     |   at java.security.AccessController.doPrivileged(Native Method)
traccar                     |   at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
traccar                     |   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
traccar                     |   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
traccar                     |   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
traccar                     |   at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

**To Reproduce**
docker -> remove container -> pull current alpine -> start container -> grab log

**Expected behavior**
normal startup of container

**Desktop (please complete the following information):**
 - OS: Debian 10.9
 - Docker: 20.10.5
 - Version: docker container alpine 4.13

**Comment by tananaev** [comment] 2021-06-03 05:26
Duplicate of https://github.com/traccar/traccar-docker/issues/74.

**Closed by tananaev** 2021-06-03 05:26 UTC
