### ISSUE TITLE
Server Down after couple of days!

### ISSUE THREAD

**Issue by sbk24** [traccar/traccar#3200] opened 2017-05-29 11:08 UTC
Hi Anton Tananaev,
can you please help with the below issue.
we are having 1700+ devices working on our traccar server.mysql database and traccar is on same server.we used open gts database and EventData table has around 1.5crore records.we have set below configurations as well as per this link.
https://www.traccar.org/optimization/
our server is getting down for every 10+ days.i think it may be because of load on mysql when ever vehicle tracking is done between some days or 
may be load from devices.can you please guide us how to resolve this issue.we are using azure cloud memory optimized server D12-v2 with 4 cores and 28gb ram.our average cpu usage as per azure report is 10-15%.it looks like server is getting down because of long sql query execution.when server is down, still some around 5 to 10% of devices still work.when we restart the server than all devices will start working.our traccar version is 3.2

increase connection limit 
ulimit -Hn: 999999
ulimit -Sn: 999999

**Comment by tananaev** [comment] 2017-05-29 11:31
Have you checked connection limit specifically for Traccar service?

If the problem is with database connection, you can try to increase `database.maxPoolSize` to something like 50. You might want to make some customisation to disallow users to request data for long periods of time, if that's what's causing the problem.

**Comment by floor1** [comment] 2017-06-16 05:52
We had the same problem, every 7 days server returned 500 - server error. we tried to increase poolsize but no luck. Traccar opens alot of connections to the database and not closing again. Did you solve the issue sbk24 ?

**Comment by tananaev** [comment] 2017-06-16 06:20
Most likely it means that your users request data for very long periods and connections get stuck on those requests.

**Comment by floor1** [comment] 2017-06-16 06:28
I just have 30 devices with 2 owners and I talked to them. They didnt request data they just use live view to see where the devices are. For me it happens VERY friday excatly between 10-15 clock.. very strange. maybe its because it reaches the excact amount of connections at that time.

**Comment by tananaev** [comment] 2017-06-16 06:34
Is database located on the same machine?

**Comment by sbk24** [comment] 2017-06-16 06:34
yes database is on same machine.

**Comment by tananaev** [comment] 2017-06-16 06:38
One recommendation is to upgrade MySQL to more recent version if it's old. I use MySQL on all demo servers without any issues. Servers run for months without any restarts.

**Comment by sbk24** [comment] 2017-06-16 06:40
**Most likely it means that your users request data for very long periods and connections get stuck on those requests.**
our user request for 1 month data.will that be problem?if so how can we rectify

**Comment by floor1** [comment] 2017-06-16 06:40
what OS are you running ? im using nginx.

**Comment by sbk24** [comment] 2017-06-16 06:42
ubuntu

**Comment by tananaev** [comment] 2017-06-16 06:43
I am using Ubuntu on most servers. `nginx` is not an OS.

One month might be a problem... depending on how much data is there.

**Comment by sbk24** [comment] 2017-06-16 06:45
data is about 1.2Crore records.will it be problem?

**Comment by tananaev** [comment] 2017-06-16 06:48
Sorry, but what's "1.2Crore"?

**Comment by sbk24** [comment] 2017-06-16 06:50
in eventdata table we have 12million records.we retrieve 1 month data from this some times.will that be problem?

**Comment by tananaev** [comment] 2017-06-16 06:56
It doesn't matter how many total records you have. How many records are you selecting?

**Comment by sbk24** [comment] 2017-06-17 02:24
it will be around 1440 to 44000 records.i just copied the wrapper log file when server got down just now.can you please check and give us solution.

INFO   | jvm 1    | 2017/06/17 01:58:34 | Exception in thread "pool-4-thread-1" java.lang.InternalError: java.io.FileNotFoundException: /usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar (Too many open files)
INFO   | jvm 1    | 2017/06/17 01:58:34 | 	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1003)
INFO   | jvm 1    | 2017/06/17 01:58:34 | 	at sun.misc.URLClassPath.getResource(URLClassPath.java:212)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.security.AccessController.doPrivileged(Native Method)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.ResourceBundle$RBClassLoader.loadClass(ResourceBundle.java:503)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2640)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1501)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1465)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1361)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.ResourceBundle.getBundle(ResourceBundle.java:845)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.logging.Level.computeLocalizedLevelName(Level.java:265)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.logging.Level.getLocalizedLevelName(Level.java:324)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.logging.SimpleFormatter.format(SimpleFormatter.java:165)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.logging.StreamHandler.publish(StreamHandler.java:211)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:116)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.logging.Logger.log(Logger.java:738)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.logging.Logger.doLog(Logger.java:765)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.logging.Logger.logp(Logger.java:1041)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at org.jboss.netty.logging.JdkLogger.warn(JdkLogger.java:80)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:340)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2017/06/17 01:58:35 | Caused by: java.io.FileNotFoundException: /usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar (Too many open files)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.zip.ZipFile.open(Native Method)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.jar.JarFile.<init>(JarFile.java:166)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.util.jar.JarFile.<init>(JarFile.java:103)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:893)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at sun.misc.URLClassPath$JarLoader.access$700(URLClassPath.java:756)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:838)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:831)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at java.security.AccessController.doPrivileged(Native Method)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:830)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1001)
INFO   | jvm 1    | 2017/06/17 01:58:35 | 	... 31 more

**Comment by tananaev** [comment] 2017-06-17 02:30
That means that you've reached the limit on number of open files.

**Comment by sbk24** [comment] 2017-06-17 02:49
can you please tell us the permanent solution for this?

**Comment by tananaev** [comment] 2017-06-17 02:51
Can I see your current limits for the Traccar process?

**Comment by sbk24** [comment] 2017-06-17 02:55
means?how can i find?is it 
ulimit -Hn: 999999
ulimit -Sn: 999999

**Comment by tananaev** [comment] 2017-06-17 02:56
Use Google. It's not a Traccar specific knowledge. There are plenty of resources about managing Linux servers out there.

**Closed** 2022-07-05 16:44 UTC
