### ISSUE TITLE
same position reported but device is moving

### ISSUE THREAD

**Issue by slachtar** [traccar/traccar#4770] opened 2021-11-10 11:49 UTC
Hello,
using latest master branch code,
log is showing same position while tracker is really moving.
Decoding Hex data from each line shows real lat and lon but log is showing same position with each line.

Remark: I'm using mySQL and updated from 4.x version to master.
Regards,

```
2021-11-08 14:01:01  INFO: [0263e878: startek < 112.97.57.228] HEX: 2626583135372c3836313135373034303030393735312c3030302c302c2c3231313130383134303130312c412c32322e3637353532312c3131342e3032313836382c31332c302e392c302c3331382c37382c32333432382c3436307c317c323533447c30364146334134372c33312c30303030303031442c30302c30302c303442317c303139437c303030307c303030302c312c3031303030307c3032303030302c2c46380d0a
2021-11-08 14:01:01  INFO: [0263e878] id: 861157040009751, time: 2021-11-08 14:01:01, lat: 22.67852, lon: 114.04617, course: 318.0
2021-11-08 14:01:11  INFO: [0263e878: startek < 112.97.57.228] HEX: 2626593135372c3836313135373034303030393735312c3030302c302c2c3231313130383134303131312c412c32322e3637353532312c3131342e3032313836382c31312c302e392c302c3331382c37382c32333432382c3436307c317c323533447c30364146334134372c33312c30303030303031442c30302c30302c303442337c303139437c303030307c303030302c312c3031303030307c3032303030302c2c46410d0a
2021-11-08 14:01:11  INFO: [0263e878] id: 861157040009751, time: 2021-11-08 14:01:11, lat: 22.67852, lon: 114.04617, course: 318.0
...
2021-11-10 11:14:29  INFO: [1529dc4f: startek < 223.104.64.151] HEX: 2626593135352c3836353432393034333331393533372c3030302c302c2c3231313131303131313432382c412c32322e3730333234362c3131342e3132393536352c33312c302e352c302c3133392c35352c32313636382c3436307c307c323633367c30303030304643392c32372c30303030303031372c30302c30302c303030347c303136377c303030307c303030302c312c3031303030307c30323030303035410d0a
2021-11-10 11:14:29  INFO: [1529dc4f] id: 865429043319537, time: 2021-11-10 11:14:28, lat: 22.67580, lon: 114.02254, course: 139.0
2021-11-10 11:14:39  INFO: [1529dc4f: startek < 223.104.64.151] HEX: 26265c3135352c3836353432393034333331393533372c3030302c302c2c3231313131303131313433382c412c32322e3730333234362c3131342e3132393536352c33312c302e352c302c3133392c35352c32313636382c3436307c307c323633367c30303030304643392c32372c30303030303031372c30302c30302c303030347c303136357c303030307c303030302c312c3031303030307c30323030303035430d0a
2021-11-10 11:14:39  INFO: [1529dc4f] id: 865429043319537, time: 2021-11-10 11:14:38, lat: 22.67580, lon: 114.02254, course: 139.0
```

**Comment by tananaev** [comment] 2021-11-10 17:45
Seems like you didn't follow the template. Please update your ticket with all the required information.

**Comment by slachtar** [comment] 2021-11-10 21:02
**Describe the bug**
I migrated from traccar-linux-64-4.10 to lastest master branch which supports VT200 startek.
First position is decoded correctly then all subsequent positions have the same lat and lon, other info changed like speed, course, time.
You can see car changing it's direction and speed without moving (same lat and lon).
Looking into log, you can see same lat and lon but when decoding the HEX the lat, lon are not those displayed in the next line of the code. Please check log below.

**To Reproduce**
Connect tracker to strartek port, and do `tail -f /opt/traccar/logs/tracker-server.log` to see traccar logs.

**Expected behavior**
Receive correct position of tracker.

**Screenshots**
see traccar log below.

**Additional context**
I'm using mySQL and user forward url.

Traccar Log:
```
2021-11-08 14:01:01  INFO: [0263e878: startek < 112.97.57.228] HEX: 2626583135372c3836313135373034303030393735312c3030302c302c2c3231313130383134303130312c412c32322e3637353532312c3131342e3032313836382c31332c302e392c302c3331382c37382c32333432382c3436307c317c323533447c30364146334134372c33312c30303030303031442c30302c30302c303442317c303139437c303030307c303030302c312c3031303030307c3032303030302c2c46380d0a
2021-11-08 14:01:01  INFO: [0263e878] id: 861157040009751, time: 2021-11-08 14:01:01, lat: 22.67852, lon: 114.04617, course: 318.0
2021-11-08 14:01:11  INFO: [0263e878: startek < 112.97.57.228] HEX: 2626593135372c3836313135373034303030393735312c3030302c302c2c3231313130383134303131312c412c32322e3637353532312c3131342e3032313836382c31312c302e392c302c3331382c37382c32333432382c3436307c317c323533447c30364146334134372c33312c30303030303031442c30302c30302c303442337c303139437c303030307c303030302c312c3031303030307c3032303030302c2c46410d0a
2021-11-08 14:01:11  INFO: [0263e878] id: 861157040009751, time: 2021-11-08 14:01:11, lat: 22.67852, lon: 114.04617, course: 318.0
...
2021-11-10 11:14:29  INFO: [1529dc4f: startek < 223.104.64.151] HEX: 2626593135352c3836353432393034333331393533372c3030302c302c2c3231313131303131313432382c412c32322e3730333234362c3131342e3132393536352c33312c302e352c302c3133392c35352c32313636382c3436307c307c323633367c30303030304643392c32372c30303030303031372c30302c30302c303030347c303136377c303030307c303030302c312c3031303030307c30323030303035410d0a
2021-11-10 11:14:29  INFO: [1529dc4f] id: 865429043319537, time: 2021-11-10 11:14:28, lat: 22.67580, lon: 114.02254, course: 139.0
2021-11-10 11:14:39  INFO: [1529dc4f: startek < 223.104.64.151] HEX: 26265c3135352c3836353432393034333331393533372c3030302c302c2c3231313131303131313433382c412c32322e3730333234362c3131342e3132393536352c33312c302e352c302c3133392c35352c32313636382c3436307c307c323633367c30303030304643392c32372c30303030303031372c30302c30302c303030347c303136357c303030307c303030302c312c3031303030307c30323030303035430d0a
2021-11-10 11:14:39  INFO: [1529dc4f] id: 865429043319537, time: 2021-11-10 11:14:38, lat: 22.67580, lon: 114.02254, course: 139.0
```

**Comment by tananaev** [comment] 2021-11-10 21:15
What makes you think it's a server issue?

**Comment by slachtar** [comment] 2021-11-10 21:28
Hello,
all data in log is coming from traccar server, also if you decode one of the positions you may notice the position is not the same as the position in log. For example, let's take 2 lines from the log:
```
2021-11-10 11:14:29  INFO: [1529dc4f: startek < 223.104.64.151] HEX: 2626593135352c3836353432393034333331393533372c3030302c302c2c3231313131303131313432382c412c32322e3730333234362c3131342e3132393536352c33312c302e352c302c3133392c35352c32313636382c3436307c307c323633367c30303030304643392c32372c30303030303031372c30302c30302c303030347c303136377c303030307c303030302c312c3031303030307c30323030303035410d0a
2021-11-10 11:14:29  INFO: [1529dc4f] id: 865429043319537, time: 2021-11-10 11:14:28, lat: 22.67580, lon: 114.02254, course: 139.0

```
an ascii version of the HEX gives:
`&&Y155,865429043319537,000,0,,211110111428,A,22.703246,114.129565,31,0.5,0,139,55,21668,460|0|2636|00000FC9,27,00000017,00,00,0004|0167|0000|0000,1,010000|0200005A`
so lat, lon are 22.703246,114.129565 
but log says  lat: 22.67580, lon: 114.02254

a side note:
I noticed that behavior also with gt06N devices after migrating, but meitrack devices continue working correctly.

**Comment by tananaev** [comment] 2021-11-10 21:36
Are you sure you don't have any coordinates filtering enabled?

**Comment by slachtar** [comment] 2021-11-10 21:53
here's my traccar.xml file.
But this happened with all gt06 devices that used to work, so I downgraded to avoid this problem. And now I'm testing on a separate server with few devices.
Could this be related to mySQL not migrated properly? I simply put the new changelog file from master branch and I've no error on traccar log.

```

    <!-- filters -->
    <entry key='filter.enable'>false</entry>
    <entry key='filter.invalid'>true</entry>
    <entry key='filter.zero'>true</entry>
    <entry key='filter.future'>7200</entry>
    <entry key='filter.maxSpeed'>270</entry>

    <!-- coordinates filter -->
    <entry key='coordinates.filter'>true</entry>
    <entry key='coordinates.minError'>10</entry>
    <entry key='coordinates.maxError'>50</entry>

    <!-- attributes copying -->
    <entry key='processing.copyAttributes.enable'>true</entry>
    <entry key='processing.copyAttributes'>ignition,blocked,power,temp0,temp1,temp2,temp3,fuel0,fuel1,odometer</entry>


    <!-- forwad url with params
        {uniqueId}, {deviceId}, {protocol}, {deviceTime}, {fixTime}, {valid}, {latitude}, {longitude}, {altitude}, {speed}, {course}, {gprmc}, {attributes}
    -->
    <entry key='forward.enable'>true</entry>
    <entry key='forward.json'>true</entry>
    <entry key='forward.url'>http://127.0.0.1:8710/data</entry>

```

**Comment by tananaev** [comment] 2021-11-10 22:01
Seems like you haven't done your due diligence before you submitted this bug, so I'm closing it. You have to test everything yourself and be absolutely sure there's a bug before submitting it here. In your case you have to test clean Traccar installation with default config first. Some of you config parameters make zero sense to me, so that's likely the cause of the behavior you are experiencing.

**Closed by tananaev** 2021-11-10 22:01 UTC
